name = "epass"
compatibility_date = "2024-07-14"
pages_build_output_dir = "./dist"

[dev]
ip = "0.0.0.0"
port = 3001

[[d1_databases]]
binding = "DB"
database_name = "epass-db"
database_id = "929baaac-1126-4b4f-8564-347bf0ac8b89"
preview_database_id = "DB"
