name = "epass"
compatibility_date = "2024-07-14"
pages_build_output_dir = "./dist"

[dev]
ip = "0.0.0.0"
port = 3001

# [[d1_databases]]
# binding = "DB"
# database_name = "northwind-demo"
# database_id = "<DATABASE_ID>"
