/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppNameSignupImport } from './routes/$appName.signup'
import { Route as AppNameSigninImport } from './routes/$appName.signin'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ExampleIndexLazyImport = createFileRoute('/example/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ExampleIndexLazyRoute = ExampleIndexLazyImport.update({
  path: '/example/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/example.index.lazy').then((d) => d.Route))

const AppNameSignupRoute = AppNameSignupImport.update({
  path: '/$appName/signup',
  getParentRoute: () => rootRoute,
} as any)

const AppNameSigninRoute = AppNameSigninImport.update({
  path: '/$appName/signin',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$appName/signin': {
      id: '/$appName/signin'
      path: '/$appName/signin'
      fullPath: '/$appName/signin'
      preLoaderRoute: typeof AppNameSigninImport
      parentRoute: typeof rootRoute
    }
    '/$appName/signup': {
      id: '/$appName/signup'
      path: '/$appName/signup'
      fullPath: '/$appName/signup'
      preLoaderRoute: typeof AppNameSignupImport
      parentRoute: typeof rootRoute
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AppNameSigninRoute,
  AppNameSignupRoute,
  ExampleIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$appName/signin",
        "/$appName/signup",
        "/example/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$appName/signin": {
      "filePath": "$appName.signin.tsx"
    },
    "/$appName/signup": {
      "filePath": "$appName.signup.tsx"
    },
    "/example/": {
      "filePath": "example.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
